version: '3.8'

services:
  devproxy:
    image: 'nginx:stable-alpine'
    container_name: devproxy
    restart: always
    ports:
      - '80:80'    # Public HTTP
      - '443:443'  # Public HTTPS
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
    networks:
      - devproxy-network

networks:
  devproxy-network:
    external: true
